import { type Order, OrderStatus, UserRole } from "@/types/admin";
import { DollarSign, ShoppingCart, Package, Clock } from "lucide-react";

//! TYPES
export interface Product {
  id: string;
  name: string;
  description: string;
  images: string[];
  price: number;
  inStock: boolean;
  stockCount: number;
  material: string;
  color: string;
  sku: string;
  sizeWidth?: number | null;
  sizeHeight?: number | null;
  sizeDepth?: number | null;
  categoryId: string;
  category: Category;
  createdAt: string | Date;
  updatedAt: string | Date;
}
export interface Category {
  id: string;
  name: string;
}

//! MOCK DATA
export const mockCategories: Category[] = [
  { id: "cat_001", name: "Electronics" },
  { id: "cat_002", name: "Clothing" },
  { id: "cat_003", name: "Home & Garden" },
  { id: "cat_004", name: "Sports" },
  { id: "cat_005", name: "Books" },
];

export const mockProducts: Product[] = [
  {
    id: "prod_001",
    name: "Dünya Haritası Tablo",
    description: "Ahşap Dünya Haritası Tablo",
    images: [
      "https://res.cloudinary.com/dwahclxhr/image/upload/v1756619032/lahlz33m3pyzaj63kjvp.jpg",
      "https://res.cloudinary.com/dwahclxhr/image/upload/v1756619028/iu6hzz89hpegllmbpxka.jpg",
      "https://res.cloudinary.com/dwahclxhr/image/upload/v1756619018/xzv08so5pzeigm1s4nrs.jpg",
    ],
    price: 299.99,
    inStock: true,
    stockCount: 50,
    material: "Ahşap",
    color: "Kahverengi",
    sku: "DH-001",
    sizeWidth: 20,
    sizeHeight: 25,
    sizeDepth: 8,
    categoryId: "cat_003",
    category: mockCategories[0],
    createdAt: new Date("2024-01-01").toISOString(),
    updatedAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "prod_002",
    name: "Ahşap Masa",
    description: "Ahşap Masa çok güzel bir masa",
    images: [
      "https://res.cloudinary.com/dwahclxhr/image/upload/v1756296214/pshfyfftklrcomocnvz8.webp",
      "https://res.cloudinary.com/dwahclxhr/image/upload/v1756296219/kndvwximszm4qifgyvxc.webp",
      "https://res.cloudinary.com/dwahclxhr/image/upload/v1756296224/dxr6wfdegxbeh59vrtg0.webp",
    ],
    price: 29.99,
    inStock: true,
    stockCount: 100,
    material: "Ahşap",
    color: "Kahverengi",
    sku: "TS-002",
    sizeWidth: 20,
    sizeHeight: 25,
    sizeDepth: 30,
    categoryId: "cat_003",
    category: mockCategories[1],
    createdAt: new Date("2024-01-02").toISOString(),
    updatedAt: new Date("2024-01-02").toISOString(),
  },
];
// Mock data for dashboard
export const mockRecentOrders: Order[] = [
  {
    id: "ord_001",
    totalPrice: 299.99,
    status: OrderStatus.PENDING,
    shippingTrackingUrl: "www.google.com",
    customizationImages: [],
    customerId: "usr_001",
    customer: {
      id: "usr_001",
      name: "John Doe",
      email: "john@example.com",
      phone: "+1234567890",
      role: UserRole.USER,
      addresses: [],
      orders: [],
      createdAt: new Date("2024-01-15"),
      updatedAt: new Date("2024-01-15"),
    },
    addressId: "addr_001",
    address: {} as any,
    items: [],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "ord_002",
    totalPrice: 149.5,
    status: OrderStatus.SHIPPED,
    shippingTrackingUrl: "https://tracking.example.com/12345",
    customizationImages: [],
    customerId: "usr_002",
    customer: {
      id: "usr_002",
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "+1234567891",
      role: UserRole.USER,
      addresses: [],
      orders: [],
      createdAt: new Date("2024-01-14"),
      updatedAt: new Date("2024-01-14"),
    },
    addressId: "addr_002",
    address: {} as any,
    items: [],
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "ord_003",
    totalPrice: 89.99,
    status: OrderStatus.DELIVERED,
    shippingTrackingUrl: "https://tracking.example.com/67890",
    customizationImages: [],
    customerId: "usr_003",
    customer: {
      id: "usr_003",
      name: "Mike Johnson",
      email: "mike@example.com",
      phone: "+1234567892",
      role: UserRole.USER,
      addresses: [],
      orders: [],
      createdAt: new Date("2024-01-13"),
      updatedAt: new Date("2024-01-13"),
    },
    addressId: "addr_003",
    address: {} as any,
    items: [],
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13"),
  },
  {
    id: "ord_004",
    totalPrice: 199.99,
    status: OrderStatus.PREPARING,
    shippingTrackingUrl: "www.google.com",
    customizationImages: [],
    customerId: "usr_004",
    customer: {
      id: "usr_004",
      name: "Sarah Wilson",
      email: "sarah@example.com",
      phone: "+1234567893",
      role: UserRole.USER,
      addresses: [],
      orders: [],
      createdAt: new Date("2024-01-12"),
      updatedAt: new Date("2024-01-12"),
    },
    addressId: "addr_004",
    address: {} as any,
    items: [],
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "ord_005",
    totalPrice: 349.99,
    status: OrderStatus.APPROVED,
    shippingTrackingUrl: "www.google.com",
    customizationImages: [],
    customerId: "usr_005",
    customer: {
      id: "usr_005",
      name: "David Brown",
      email: "david@example.com",
      phone: "+1234567894",
      role: UserRole.USER,
      addresses: [],
      orders: [],
      createdAt: new Date("2024-01-11"),
      updatedAt: new Date("2024-01-11"),
    },
    addressId: "addr_005",
    address: {} as any,
    items: [],
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-11"),
  },
];

export const mockRevenueData = [
  { day: "Mon", revenue: 2400 },
  { day: "Tue", revenue: 1398 },
  { day: "Wed", revenue: 9800 },
  { day: "Thu", revenue: 3908 },
  { day: "Fri", revenue: 4800 },
  { day: "Sat", revenue: 3800 },
  { day: "Sun", revenue: 4300 },
];

export const mockDashboardStats = [
  {
    title: "Total Revenue",
    value: "$45,231.89",
    change: "+20.1% from last month",
    icon: DollarSign,
  },
  {
    title: "Total Sales",
    value: "+2350",
    change: "+180.1% from last month",
    icon: ShoppingCart,
  },
  {
    title: "Active Products",
    value: "573",
    change: "+19% from last month",
    icon: Package,
  },
  {
    title: "Pending Orders",
    value: "12",
    change: "+201 since last hour",
    icon: Clock,
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord_001",
    totalPrice: 299.99,
    status: OrderStatus.PENDING,
    shippingTrackingUrl: "www.google.com",
    customizationImages: [],
    customerId: "usr_001",
    customer: {
      id: "usr_001",
      name: "John Doe",
      email: "john@example.com",
      phone: "+1234567890",
      role: UserRole.USER,
      addresses: [],
      orders: [],
      createdAt: new Date("2024-01-15"),
      updatedAt: new Date("2024-01-15"),
    },
    addressId: "addr_001",
    address: {
      id: "addr_001",
      addressTitle: "Home",
      ulke: "USA",
      sehir: "New York",
      mahalle: "Manhattan",
      sokak: "5th Avenue",
      no: "123",
      postaKodu: "10001",
      tarif: "Near Central Park",
      varsayilan: true,
      userId: "usr_001",
      user: {} as any,
      orders: [],
      createdAt: new Date("2024-01-15"),
      updatedAt: new Date("2024-01-15"),
    },
    items: [
      {
        id: "item_001",
        quantity: 1,
        price: 299.99,
        orderId: "ord_001",
        order: {} as any,
        productId: "prod_001",
        product: mockProducts[0],
      },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "ord_002",
    totalPrice: 149.5,
    status: OrderStatus.SHIPPED,
    shippingTrackingUrl: "https://tracking.example.com/12345",
    customizationImages: [],
    customerId: "usr_002",
    customer: {
      id: "usr_002",
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "+1234567891",
      role: UserRole.USER,
      addresses: [],
      orders: [],
      createdAt: new Date("2024-01-14"),
      updatedAt: new Date("2024-01-14"),
    },
    addressId: "addr_002",
    address: {
      id: "addr_002",
      addressTitle: "Office",
      ulke: "USA",
      sehir: "Los Angeles",
      mahalle: "Downtown",
      sokak: "Main Street",
      no: "456",
      postaKodu: "90001",
      tarif: "Business district",
      varsayilan: false,
      userId: "usr_002",
      user: {} as any,
      orders: [],
      createdAt: new Date("2024-01-14"),
      updatedAt: new Date("2024-01-14"),
    },
    items: [
      {
        id: "item_002",
        quantity: 5,
        price: 29.99,
        orderId: "ord_002",
        order: {} as any,
        productId: "prod_002",
        product: mockProducts[1],
      },
    ],
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
  },
  {
    id: "ord_003",
    totalPrice: 89.99,
    status: OrderStatus.DELIVERED,
    shippingTrackingUrl: "https://tracking.example.com/67890",
    customizationImages: [],
    customerId: "usr_003",
    customer: {
      id: "usr_003",
      name: "Mike Johnson",
      email: "mike@example.com",
      phone: "+1234567892",
      role: UserRole.USER,
      addresses: [],
      orders: [],
      createdAt: new Date("2024-01-13"),
      updatedAt: new Date("2024-01-13"),
    },
    addressId: "addr_003",
    address: {
      id: "addr_003",
      addressTitle: "Home",
      ulke: "USA",
      sehir: "Chicago",
      mahalle: "Lincoln Park",
      sokak: "Lake Shore Drive",
      no: "789",
      postaKodu: "60601",
      tarif: "Near the lake",
      varsayilan: true,
      userId: "usr_003",
      user: {} as any,
      orders: [],
      createdAt: new Date("2024-01-13"),
      updatedAt: new Date("2024-01-13"),
    },
    items: [
      {
        id: "item_003",
        quantity: 1,
        price: 49.99,
        orderId: "ord_003",
        order: {} as any,
        productId: "prod_003",
        product: mockProducts[2],
      },
      {
        id: "item_004",
        quantity: 1,
        price: 39.99,
        orderId: "ord_003",
        order: {} as any,
        productId: "prod_005",
        product: mockProducts[4],
      },
    ],
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13"),
  },
];
